version: 0.1

phases:
  pre_build:
    commands:
      - echo Fetching tokens
      - wget http://larsbotcredentials.s3-eu-west-2.amazonaws.com
  build:
    commands:
    - echo Build started...
    - chmod +x gradlew
    - ./gradlew installDist
artifacts:
  files:
  - build/install/**/*
  - appspec.yml